Procster: conf/covmodels.c File Reference
covmodels.c File Reference
Coverity models
Macros
#define MHD_YES 1
Typedefs
typedef void * json_t
typedef void * GSList
typedef void * proc_t
Functions
struct MHD_Response * MHD_create_response_from_buffer (size_t size, void *buffer, enum MHD_ResponseMemoryMode mode)
struct MHD_Response * MHD_create_response_from_fd (size_t size, int fd)
void MHD_destroy_response (struct MHD_Response *response)
int MHD_add_response_header (struct MHD_Response *response, const char *header, const char *content)
void json_delete (json_t *json)
void g_slist_free (GSList *list)
void freeproc (proc_t *p)
Detailed Description
Coverity models
Model free()ing functions for branching data structures, where coverity does not recognize the free()ing functions or their behavior. Allocating and freeing functions should be modeled as pairs
Try compile by (Also: -of):
Test Compile: gcc -c covmodels.c
Be prepared for "warning: implicit declaration of function ..."
cov-make-library –output-file covint/covmodels.xmldb covmodels.c
See headers:
/usr/include/microhttpd.h
/usr/include/jansson.h
/usr/include/glib-2.0/glib/gslist.h
TODO
Create headers for __coverity_... functions ?
Macro Definition Documentation
MHD_YES
#define MHD_YES 1
Referenced by answer_to_connection(), answer_to_connection1(), handle_request(), MHD_add_response_header(), ms_on_client_connect(), and post_body_parse().
Typedef Documentation
GSList
typedef void* GSList
json_t
typedef void* json_t
proc_t
typedef void* proc_t
Function Documentation
freeproc()
void freeproc (proc_t * p)
Referenced by ptree_free().
g_slist_free()
void g_slist_free (GSList * list)
Referenced by proc_tree(), and ptree_free().
json_delete()
void json_delete (json_t * json)
MHD_add_response_header()
int MHD_add_response_header (struct MHD_Response * response, const char * header, const char * content)
References MHD_YES.
Referenced by answer_to_connection(), answer_to_connection0(), answer_to_connection1(), handle_request(), and ms_answer_to_connection().
MHD_create_response_from_buffer()
struct MHD_Response* MHD_create_response_from_buffer (size_t size, void * buffer, enum MHD_ResponseMemoryMode mode)
Referenced by answer_to_connection(), answer_to_connection0(), answer_to_connection1(), handle_request(), ms_answer_to_connection(), and send_page().
MHD_create_response_from_fd()
struct MHD_Response* MHD_create_response_from_fd (size_t size, int fd)
Referenced by req_trystatic(), and trystatic().
MHD_destroy_response()
void MHD_destroy_response (struct MHD_Response * response)
Referenced by answer_to_connection(), answer_to_connection0(), answer_to_connection1(), handle_request(), ms_answer_to_connection(), and send_page().