Procster: json_example.c File Reference
json_example.c File Reference
#include <string>
#include <vector>
#include <sstream>
#include <iostream>
#include <cstring>
#include <microhttpd.h>
Data Structures
struct ConnectionData
Functions
int handle_request (void *cls, struct MHD_Connection *connection, const char *url, const char *method, const char *version, const char *upload_data, size_t *upload_data_size, void **con_cls)
int main (int argc, char **argv)
Function Documentation
handle_request()
int handle_request (void * cls, struct MHD_Connection * connection, const char * url, const char * method, const char * version, const char * upload_data, size_t * upload_data_size, void ** con_cls)
References ConnectionData::is_parsing, MHD_add_response_header(), MHD_create_response_from_buffer(), MHD_destroy_response(), MHD_YES, and ConnectionData::read_post_data.
Referenced by main().
main()
int main (int argc, char ** argv)
References handle_request().
Referenced by proc_list_json2(), and proc_tree().