Procster: ms_test.c File Reference
ms_test.c File Reference
#include <jansson.h>
#include "proclister.h"
Functions
int hdl_hello (request *req, response *res)
Miniserver testbed.
int hdl_bye (request *req, response *res)
int hdl_json (request *req, response *res)
int main (int argc, char **argv)
Variables
static action actarr []
Function Documentation
hdl_bye()
int hdl_bye (request * req, response * res)
References response::cont, and response::contlen.
hdl_hello()
int hdl_hello (request * req, response * res)
Miniserver testbed.
References response::cont, and response::contlen.
hdl_json()
int hdl_json (request * req, response * res)
References response::conttype, and response::json.
main()
int main (int argc, char ** argv)
References actarr, action_find(), miniserver::actions, action::actlbl, miniserver::docroot, action::hdlr, miniserver::port, miniserver::server, server_actions_load(), server_new(), and server_run().
Variable Documentation
actarr
action actarr[] static
Initial value:
= {
  {.actlbl = "hello", .url = "/hello", .hdlr = hdl_hello},
  {.actlbl = "bye", .url = "/bye", .hdlr = hdl_bye},
  {.actlbl = "json", .url = "/json", .hdlr = hdl_json, .conttype = "application/json"}
}
Referenced by main().