Procster: ulftest.c File Reference
ulftest.c File Reference
#include <string.h>
#include <ulfius.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
Macros
#define PORT 8537
Ulfius Framework example program.
#define PREFIX "/test"
#define PREFIXJSON "/testjson"
#define PREFIXCOOKIE "/testcookie"
Functions
int callback_get_test (const struct _u_request *request, struct _u_response *response, void *user_data)
callback functions declaration
int callback_get_empty_response (const struct _u_request *request, struct _u_response *response, void *user_data)
Callback function that put an empty response and a status 200.
int callback_post_test (const struct _u_request *request, struct _u_response *response, void *user_data)
Callback function that put a "Hello World!" and the post parameters send by the client in the response.
int callback_all_test_foo (const struct _u_request *request, struct _u_response *response, void *user_data)
Callback function that put "Hello World!" and all the data sent by the client in the response as string (http method, url, params, cookies, headers, post, json, and user specific data in the response.
int callback_get_cookietest (const struct _u_request *request, struct _u_response *response, void *user_data)
Callback function that sets cookies in the response The counter cookie is incremented every time the client reloads this url.
int callback_default (const struct _u_request *request, struct _u_response *response, void *user_data)
Default callback function called if no endpoint has a match.
char * print_map (const struct _u_map *map)
decode a u_map into a string
char * read_file (const char *filename)
int main (int argc, char **argv)
Macro Definition Documentation
PORT
#define PORT 8537
Ulfius Framework example program.
This example program describes the main features that are available in a callback function
Copyright 2015-2017 Nicolas Mora mail@.nosp@m.babe.nosp@m.loues.nosp@m.t.or.nosp@m.g
License MIT
Referenced by main().
PREFIX
#define PREFIX "/test"
Referenced by main().
PREFIXCOOKIE
#define PREFIXCOOKIE "/testcookie"
Referenced by main().
PREFIXJSON
#define PREFIXJSON "/testjson"
Function Documentation
callback_all_test_foo()
int callback_all_test_foo (const struct _u_request * request, struct _u_response * response, void * user_data)
Callback function that put "Hello World!" and all the data sent by the client in the response as string (http method, url, params, cookies, headers, post, json, and user specific data in the response.
References print_map().
Referenced by main().
callback_default()
int callback_default (const struct _u_request * request, struct _u_response * response, void * user_data)
Default callback function called if no endpoint has a match.
Referenced by main().
callback_get_cookietest()
int callback_get_cookietest (const struct _u_request * request, struct _u_response * response, void * user_data)
Callback function that sets cookies in the response The counter cookie is incremented every time the client reloads this url.
Referenced by main().
callback_get_empty_response()
int callback_get_empty_response (const struct _u_request * request, struct _u_response * response, void * user_data)
Callback function that put an empty response and a status 200.
Referenced by main().
callback_get_test()
int callback_get_test (const struct _u_request * request, struct _u_response * response, void * user_data)
callback functions declaration
Callback function that put a "Hello World!" string in the response.
Referenced by main().
callback_post_test()
int callback_post_test (const struct _u_request * request, struct _u_response * response, void * user_data)
Callback function that put a "Hello World!" and the post parameters send by the client in the response.
References print_map().
Referenced by main().
main()
int main (int argc, char ** argv)
References callback_all_test_foo(), callback_default(), callback_get_cookietest(), callback_get_empty_response(), callback_get_test(), callback_post_test(), PORT, PREFIX, PREFIXCOOKIE, and read_file().
print_map()
char* print_map (const struct _u_map * map)
decode a u_map into a string
Referenced by callback_all_test_foo(), and callback_post_test().
read_file()
char* read_file (const char * filename)
Referenced by main().