# Install Procster on a large number of machines
# Chores before running (Do this setup once per many machines if files are on NFS, rechable by all machines)
# - Install NPM dependencies: npm install
# - Make sure procster config ~/.procster/procster.conf.json exists and is configured
#   - cp procster.conf.json ~/.procster/procster.conf.json
#   - Edit and configure for your environment
#   - Run "make unit" to preview before running ansible
- name: Install procster
  become: yes
  hosts: '{{ host }}'
  vars:
    mustache: ./node_modules/mustache/bin/mustache
    sysdunit: procster.service
    docroot: /home/mrsmith/procster
  tasks:
    # Already have this in debug: var=ansible_env.PWD ? {{ lookup('env','PWD') }} ?
    - name: Detect current dir
      shell: pwd
      register: currdir
    - debug: var=currdir.stdout
    - name: Generate Config
      # ./node_modules/mustache/bin/mustache - ./tmpl/default.installer.menu.mustache > /tmp/default
      shell: cat {{ currdir.stdout }}/.procster/procster.conf.json | {{ currdir.stdout }}{{ mustache }} -  {{ currdir.stdout }}conf/procster.service.mustache > ./procster.service
      delegate_to: localhost
    # If unit file is on NFS we can have systemd symlink it
    # Otherwise copy to host local service account homedir (?)
    - name: Enable and start service
      # 
      shell: 'systemctl enable --now {{ currdir.stdout }}/procster.service'
    # TODO: Place to stop
    # procster.service unit should be installed by now
    - name: Stop Service
      shell: 'systemctl stop procster'
      when: 0
